name: PrincehouseLiving
favicon: null
layout_spectrum: 0.12737188627943397
typography_spectrum: 0.5081179440021515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.396729982458055
  lightness: 0.15493551036342978
  saturation: 0.36155789135955274
  rhythmicContrast: 0.9154587658122182
purpose: []
